# Generated by Django 4.1.7 on 2023-03-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c01',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c02',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c03',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c04',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c05',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c06',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c07',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c08',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c09',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='c11',
            field=models.IntegerField(default=0),
        ),
    ]
